// client/src/components/Register.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { deriveKey } from '../crypto/argon2';
import { generateIdentityKeyPair, generateSigningKeyPair, exportKeyPair, exportSigningKeyPair } from '../crypto/keys';
import { storeKeys, clearAllData } from '../db/indexeddb';

const API = '/api';

function validatePassword(pw) {
  if (pw.length < 12) return 'Password must be at least 12 characters';
  if (!/[A-Z]/.test(pw)) return 'Password must contain an uppercase letter';
  if (!/[a-z]/.test(pw)) return 'Password must contain a lowercase letter';
  if (!/[0-9]/.test(pw)) return 'Password must contain a number';
  if (!/[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(pw)) return 'Password must contain a special character like @';
  return null;
}

export default function Register() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  async function handleSubmit(e) {
    e.preventDefault();
    setLoading(true);
    setError('');

    const pwError = validatePassword(password);
    if (pwError) {
      setError(pwError);
      setLoading(false);
      return;
    }

    try {
      const identityKeyPair = await generateIdentityKeyPair();
      const signingKeyPair = await generateSigningKeyPair();
      const identityExported = await exportKeyPair(identityKeyPair);
      const signingExported = await exportSigningKeyPair(signingKeyPair);

      const salt = crypto.getRandomValues(new Uint8Array(16));
      const masterKey = await deriveKey(password, salt);
      const passwordVerifier = masterKey;

      const backupKey = await deriveBackupKey(masterKey, salt);
      const iv = crypto.getRandomValues(new Uint8Array(12));

      const identityPrivJwk = await crypto.subtle.exportKey('jwk', identityKeyPair.privateKey);
      const signingPrivJwk = await crypto.subtle.exportKey('jwk', signingKeyPair.privateKey);
      const backupPayload = new TextEncoder().encode(JSON.stringify({
        identity: identityPrivJwk,
        signing: signingPrivJwk
      }));
      const encryptedPriv = await crypto.subtle.encrypt(
        { name: 'AES-GCM', iv }, backupKey, backupPayload
      );

      const backup = new Uint8Array(iv.length + encryptedPriv.byteLength);
      backup.set(iv);
      backup.set(new Uint8Array(encryptedPriv), iv.length);

      const usernameHash = await sha256(new TextEncoder().encode(username));
      const emailHash = email ? await sha256(new TextEncoder().encode(email)) : null;

      const res = await fetch(`${API}/auth/register`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          usernameHash: b64(usernameHash),
          emailHash: emailHash ? b64(emailHash) : null,
          argon2Salt: b64(salt),
          passwordVerifier: b64(passwordVerifier),
          identityPublicKey: b64(identityExported.publicKey),
          signingPublicKey: b64(signingExported.publicKey),
          encryptedKeyBackup: b64(backup)
        })
      });

      let data;
      const contentType = res.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
        data = await res.json();
      } else {
        const text = await res.text();
        throw new Error(text || `Server error: ${res.status}`);
      }

      if (!res.ok) throw new Error(data.error || `Registration failed (${res.status})`);

      const { token } = data;
      await clearAllData(); // wipe old account data
      await storeKeys(identityExported, signingExported, masterKey);

      const encryptedUsername = await encryptUsername(username, masterKey);
      localStorage.setItem('token', token);
      localStorage.setItem('username', encryptedUsername);
      navigate('/chat');
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-card">
        <h2>Create Account</h2>
        <p>Your keys are generated in the browser. We never see your password.</p>
        <form onSubmit={handleSubmit}>
          <input placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} required />
          <input type="password" placeholder="Password (12+ chars, A-Z, a-z, 0-9, special)" value={password} onChange={e => setPassword(e.target.value)} required />
          <input type="email" placeholder="Email (optional)" value={email} onChange={e => setEmail(e.target.value)} />
          {error && <div className="error">{error}</div>}
          <button type="submit" disabled={loading}>{loading ? 'Generating keys...' : 'Register'}</button>
        </form>
        <p style={{ marginTop: 16, textAlign: 'center', fontSize: 13 }}>
          Already have an account? <Link to="/login" style={{ color: '#5865F2', textDecoration: 'none' }}>Log in</Link>
        </p>
      </div>
    </div>
  );
}

async function deriveBackupKey(masterKey, salt) {
  const base = await crypto.subtle.importKey('raw', masterKey, 'HKDF', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt, info: new TextEncoder().encode('backup') },
    base, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']
  );
}

async function sha256(data) {
  return new Uint8Array(await crypto.subtle.digest('SHA-256', data));
}

function b64(bytes) {
  return btoa(String.fromCharCode(...bytes));
}

async function encryptUsername(username, masterKey) {
  const encKey = await crypto.subtle.importKey('raw', masterKey, 'AES-GCM', false, ['encrypt']);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    encKey,
    new TextEncoder().encode(username)
  );
  const combined = new Uint8Array(iv.length + ciphertext.byteLength);
  combined.set(iv);
  combined.set(new Uint8Array(ciphertext), iv.length);
  return b64(combined);
}

// client/src/routes/register/+page.svelte
<script>
  import { goto } from '$app/navigation';
  import { generateIdentityKeyPair, generateSigningKeyPair, deriveKey, storeKeys } from '$lib/crypto/index.js';
  import { sha256 } from '@noble/hashes/sha2.js';
  import { auth } from '$lib/stores/auth.js';

  let username = '';
  let password = '';
  let email = '';
  let confirmPassword = '';
  let error = '';
  let loading = false;

  async function handleRegister() {
    error = '';
    if (!username || !password) {
      error = 'Username and password are required';
      return;
    }
    if (password !== confirmPassword) {
      error = 'Passwords do not match';
      return;
    }
    if (password.length < 12) {
      error = 'Password must be at least 12 characters';
      return;
    }

    loading = true;
    try {
      const encoder = new TextEncoder();
      const usernameBytes = encoder.encode(username.normalize('NFKC').toLowerCase());
      const usernameHash = sha256(usernameBytes);
      const emailHash = email ? sha256(encoder.encode(email.normalize('NFKC').toLowerCase())) : null;

      const salt = crypto.getRandomValues(new Uint8Array(16));
      const masterKey = await deriveKey(password, salt);
      const passwordVerifier = sha256(masterKey);

      const identityKP = generateIdentityKeyPair();
      const signingKP = generateSigningKeyPair();

      const iv = crypto.getRandomValues(new Uint8Array(12));
      const keyMaterial = await crypto.subtle.importKey('raw', masterKey, 'AES-GCM', false, ['encrypt']);
      const combinedPriv = new Uint8Array(64);
      combinedPriv.set(identityKP.privateKey, 0);
      combinedPriv.set(signingKP.privateKey, 32);
      const encryptedBackup = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, keyMaterial, combinedPriv);
      const encryptedKeyBackup = new Uint8Array(iv.length + encryptedBackup.byteLength);
      encryptedKeyBackup.set(iv, 0);
      encryptedKeyBackup.set(new Uint8Array(encryptedBackup), iv.length);

      const body = {
        usernameHash: btoa(String.fromCharCode(...usernameHash)),
        argon2Salt: btoa(String.fromCharCode(...salt)),
        passwordVerifier: btoa(String.fromCharCode(...passwordVerifier)),
        identityPublicKey: btoa(String.fromCharCode(...identityKP.publicKey)),
        signingPublicKey: btoa(String.fromCharCode(...signingKP.publicKey)),
        encryptedKeyBackup: btoa(String.fromCharCode(...encryptedKeyBackup))
      };
      if (emailHash) body.emailHash = btoa(String.fromCharCode(...emailHash));

      const res = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Registration failed');
      }

      const { token } = await res.json();
      await storeKeys(identityKP.privateKey, signingKP.privateKey, usernameHash);
      auth.login(token, null, usernameHash);
      goto('/settings/keys');
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }
</script>

<div class="container">
  <h1 class="page-title">Create Account</h1>
  <p class="page-subtitle">Your keys stay on your device</p>

  <div class="card">
    <div class="form-group">
      <label for="username">Username</label>
      <input id="username" type="text" bind:value={username} placeholder="Choose a username" />
    </div>

    <div class="form-group">
      <label for="email">Email (optional)</label>
      <input id="email" type="email" bind:value={email} placeholder="you@example.com" />
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input id="password" type="password" bind:value={password} placeholder="At least 12 characters" />
    </div>

    <div class="form-group">
      <label for="confirm">Confirm Password</label>
      <input id="confirm" type="password" bind:value={confirmPassword} placeholder="Repeat password" />
    </div>

    {#if error}<p class="error">{error}</p>{/if}

    <button class="btn" on:click={handleRegister} disabled={loading} style="width:100%;">
      {#if loading}<span class="spinner"></span>{/if}
      Create Account
    </button>

    <p style="text-align:center; margin-top:1rem; color:var(--text-muted); font-size:0.875rem;">
      Already have an account? <a href="/login">Sign in</a>
    </p>
  </div>
</div>
