// client/src/routes/login/+page.svelte
<script>
  import { goto } from '$app/navigation';
  import { deriveKey, storeKeys } from '$lib/crypto/index.js';
  import { sha256 } from '@noble/hashes/sha2.js';
  import { auth } from '$lib/stores/auth.js';
  import { onMount } from 'svelte';

  let username = '';
  let password = '';
  let totpCode = '';
  let recoveryCode = '';
  let error = '';
  let loading = false;
  let step = 'credentials';
  let challengeData = null;
  let usernameHash = null;

  onMount(() => {
    if ($auth.isAuthenticated) goto('/settings/keys');
  });

  async function handleChallenge() {
    error = '';
    if (!username || !password) {
      error = 'Username and password are required';
      return;
    }

    loading = true;
    try {
      const encoder = new TextEncoder();
      usernameHash = sha256(encoder.encode(username.normalize('NFKC').toLowerCase()));
      const usernameHashB64 = btoa(String.fromCharCode(...usernameHash));

      const res = await fetch('/api/auth/login/challenge', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ usernameHash: usernameHashB64 })
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Invalid credentials');
      }

      challengeData = await res.json();
      const salt = Uint8Array.from(atob(challengeData.salt), c => c.charCodeAt(0));
      const masterKey = await deriveKey(password, salt);
      const passwordVerifier = sha256(masterKey);

      const challengeBytes = Uint8Array.from(atob(challengeData.challenge), c => c.charCodeAt(0));
      const hmacKey = await crypto.subtle.importKey('raw', passwordVerifier, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
      const hmacResponse = new Uint8Array(await crypto.subtle.sign('HMAC', hmacKey, challengeBytes));

      if (challengeData.requiresTOTP) {
        step = 'totp';
        loading = false;
        return;
      }

      await verifyLogin(hmacResponse);
    } catch (err) {
      error = err.message;
      loading = false;
    }
  }

  async function verifyLogin(hmacResponse, totp = null, recovery = null) {
    try {
      const usernameHashB64 = btoa(String.fromCharCode(...usernameHash));
      const body = {
        usernameHash: usernameHashB64,
        hmacResponse: btoa(String.fromCharCode(...hmacResponse))
      };
      if (totp) body.totpCode = totp;
      if (recovery) body.recoveryCode = recovery;

      const res = await fetch('/api/auth/login/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Login failed');
      }

      const data = await res.json();
      const encryptedKeyBackup = Uint8Array.from(atob(data.encryptedKeyBackup), c => c.charCodeAt(0));
      const salt = Uint8Array.from(atob(challengeData.salt), c => c.charCodeAt(0));
      const masterKey = await deriveKey(password, salt);

      const iv = encryptedKeyBackup.slice(0, 12);
      const ciphertext = encryptedKeyBackup.slice(12);
      const keyMaterial = await crypto.subtle.importKey('raw', masterKey, 'AES-GCM', false, ['decrypt']);
      const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, keyMaterial, ciphertext);

      const combined = new Uint8Array(decrypted);
      const identityPrivateKey = combined.slice(0, 32);
      const signingPrivateKey = combined.slice(32, 64);

      await storeKeys(identityPrivateKey, signingPrivateKey, usernameHash);
      auth.login(data.token, null, usernameHash);
      goto('/settings/keys');
    } catch (err) {
      error = err.message;
      loading = false;
    }
  }

  async function handleTOTP() {
    error = '';
    loading = true;
    const salt = Uint8Array.from(atob(challengeData.salt), c => c.charCodeAt(0));
    const masterKey = await deriveKey(password, salt);
    const passwordVerifier = sha256(masterKey);
    const challengeBytes = Uint8Array.from(atob(challengeData.challenge), c => c.charCodeAt(0));
    const hmacKey = await crypto.subtle.importKey('raw', passwordVerifier, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
    const hmacResponse = new Uint8Array(await crypto.subtle.sign('HMAC', hmacKey, challengeBytes));

    if (totpCode) {
      await verifyLogin(hmacResponse, totpCode, null);
    } else if (recoveryCode) {
      await verifyLogin(hmacResponse, null, recoveryCode);
    } else {
      error = 'Enter TOTP code or recovery code';
      loading = false;
    }
  }
</script>

<div class="container">
  <h1 class="page-title">Sign In</h1>
  <p class="page-subtitle">Welcome back to CypherChat</p>

  <div class="card">
    {#if step === 'credentials'}
      <div class="form-group">
        <label for="username">Username</label>
        <input id="username" type="text" bind:value={username} placeholder="Your username" />
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" bind:value={password} placeholder="Your password" />
      </div>

      {#if error}<p class="error">{error}</p>{/if}

      <button class="btn" on:click={handleChallenge} disabled={loading} style="width:100%;">
        {#if loading}<span class="spinner"></span>{/if}
        Sign In
      </button>

    {:else if step === 'totp'}
      <p style="text-align:center; margin-bottom:1rem;">Two-factor authentication required</p>

      <div class="form-group">
        <label for="totp">6-digit TOTP Code</label>
        <input id="totp" type="text" bind:value={totpCode} placeholder="000000" maxlength="6" inputmode="numeric" />
      </div>

      <div class="form-group">
        <label for="recovery">Or Recovery Code</label>
        <input id="recovery" type="text" bind:value={recoveryCode} placeholder="xxxx-xxxx-xxxx" />
      </div>

      {#if error}<p class="error">{error}</p>{/if}

      <button class="btn" on:click={handleTOTP} disabled={loading} style="width:100%;">
        {#if loading}<span class="spinner"></span>{/if}
        Verify
      </button>

      <button class="btn btn-secondary" on:click={() => { step = 'credentials'; totpCode = ''; recoveryCode = ''; error = ''; }} style="width:100%; margin-top:0.5rem;">
        Back
      </button>
    {/if}

    <p style="text-align:center; margin-top:1rem; color:var(--text-muted); font-size:0.875rem;">
      Don't have an account? <a href="/register">Create one</a>
    </p>
  </div>
</div>

// client/src/components/Login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { deriveKey } from '../crypto/argon2';
import { importKeyPair, importSigningKeyPair } from '../crypto/keys';
import { storeKeys } from '../db/indexeddb';

const API = '/api';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [totpCode, setTotpCode] = useState('');
  const [step, setStep] = useState('password');
  const [challengeData, setChallengeData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  async function handlePassword(e) {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const usernameHash = await sha256(new TextEncoder().encode(username));
      const res = await fetch(`${API}/auth/login/challenge`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ usernameHash: b64(usernameHash) })
      });

      let data;
      const ct = res.headers.get('content-type');
      if (ct && ct.includes('application/json')) {
        data = await res.json();
      } else {
        const text = await res.text();
        throw new Error(text || `Server error: ${res.status}`);
      }

      const salt = fromB64(data.salt);
      const masterKey = await deriveKey(password, salt);
      const challenge = fromB64(data.challenge);
      const response = await hmacSHA256(masterKey, challenge);

      const payload = {
        usernameHash: b64(usernameHash),
        response: b64(response),
        requiresTOTP: data.requiresTOTP,
        salt: b64(salt)
      };

      setChallengeData(payload);
      if (data.requiresTOTP) setStep('totp');
      else await finishLogin(payload, masterKey);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleTOTP(e) {
    e.preventDefault();
    setLoading(true);
    await finishLogin({ ...challengeData, totpCode }, null);
    setLoading(false);
  }

  async function finishLogin(payload, cachedMasterKey) {
    try {
      const res = await fetch(`${API}/auth/login/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      let data;
      const ct = res.headers.get('content-type');
      if (ct && ct.includes('application/json')) {
        data = await res.json();
      } else {
        const text = await res.text();
        throw new Error(text || `Server error: ${res.status}`);
      }

      if (!res.ok) throw new Error(data.error || 'Login failed');

      const { token, encryptedKeyBackup, identityPublicKey, signingPublicKey } = data;

      const salt = fromB64(challengeData.salt);
      const masterKey = cachedMasterKey || await deriveKey(password, salt);

      const backupKey = await deriveBackupKey(masterKey, salt);
      const backupBytes = fromB64(encryptedKeyBackup);
      const iv = backupBytes.slice(0, 12);
      const cipher = backupBytes.slice(12);
      const backupPayload = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, backupKey, cipher);
      const backupJson = JSON.parse(new TextDecoder().decode(backupPayload));
      
      const pubBytes = fromB64(identityPublicKey);
      const sigPubBytes = fromB64(signingPublicKey);
      const identityPrivBytes = base64urlToBytes(backupJson.identity.d);
      const signingPrivBytes = base64urlToBytes(backupJson.signing.d);

      const keyPair = await importKeyPair(pubBytes, identityPrivBytes);
      const signingKeyPair = await importSigningKeyPair(sigPubBytes, signingPrivBytes);

      await storeKeys(
        { publicKey: pubBytes, privateKey: identityPrivBytes },
        { publicKey: sigPubBytes, privateKey: signingPrivBytes },
        masterKey
      );
      
      const encryptedUsername = await encryptUsername(username, masterKey);
      localStorage.setItem('token', token);
      localStorage.setItem('username', encryptedUsername);
      navigate('/chat');
    } catch (err) {
      setError(err.message);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-card">
        <h2>Welcome back</h2>
        <p>Log in to your secure messenger.</p>
        {step === 'password' ? (
          <form onSubmit={handlePassword}>
            <input placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} required />
            <input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} required />
            {error && <div className="error">{error}</div>}
            <button type="submit" disabled={loading}>{loading ? 'Authenticating...' : 'Log In'}</button>
          </form>
        ) : (
          <form onSubmit={handleTOTP}>
            <p style={{ marginBottom: 12, color: 'var(--text-secondary)' }}>Enter the 6-digit code from your authenticator</p>
            <input value={totpCode} onChange={e => setTotpCode(e.target.value)} maxLength={6} placeholder="000000" required />
            {error && <div className="error">{error}</div>}
            <button type="submit" disabled={loading}>{loading ? 'Verifying...' : 'Verify'}</button>
          </form>
        )}
        <p style={{ marginTop: 16, textAlign: 'center', fontSize: 13 }}>
          Need an account? <Link to="/register" style={{ color: '#5865F2', textDecoration: 'none' }}>Register</Link>
        </p>
      </div>
    </div>
  );
}

async function deriveBackupKey(masterKey, salt) {
  const base = await crypto.subtle.importKey('raw', masterKey, 'HKDF', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt, info: new TextEncoder().encode('backup') },
    base, { name: 'AES-GCM', length: 256 }, false, ['decrypt']
  );
}

async function sha256(data) {
  return new Uint8Array(await crypto.subtle.digest('SHA-256', data));
}

async function hmacSHA256(key, data) {
  const ckey = await crypto.subtle.importKey('raw', key, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return new Uint8Array(await crypto.subtle.sign('HMAC', ckey, data));
}

function b64(bytes) {
  return btoa(String.fromCharCode(...bytes));
}

function fromB64(str) {
  const b = atob(str);
  return new Uint8Array([...b].map(c => c.charCodeAt(0)));
}

function base64urlToBytes(str) {
  const pad = '='.repeat((4 - str.length % 4) % 4);
  const base64 = str.replace(/-/g, '+').replace(/_/g, '/') + pad;
  const bin = atob(base64);
  return new Uint8Array([...bin].map(c => c.charCodeAt(0)));
}

async function encryptUsername(username, masterKey) {
  const encKey = await crypto.subtle.importKey('raw', masterKey, 'AES-GCM', false, ['encrypt']);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    encKey,
    new TextEncoder().encode(username)
  );
  const combined = new Uint8Array(iv.length + ciphertext.byteLength);
  combined.set(iv);
  combined.set(new Uint8Array(ciphertext), iv.length);
  return b64(combined);
}
